better control of make

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1724,6 +1724,12 @@ fi
 # Now substitute these variables in src/Makevars.in to create src/Makevars
 
 
+
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
 ##AC_SUBST(RCPP_LDFLAGS)
 
 make -C inst/dap-master/torus_src
